# Generated by Django 3.2.5 on 2022-11-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='managerid',
            field=models.IntegerField(),
        ),
    ]
