# Generated by Django 3.2.5 on 2022-12-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0003_alter_employee_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photograph',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
