# Generated by Django 3.2.5 on 2022-12-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0006_alter_employee_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photograph',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
