# Generated by Django 3.2.5 on 2022-12-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0008_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateid', models.IntegerField()),
                ('cityid', models.IntegerField()),
                ('cityname', models.CharField(default='', max_length=45)),
            ],
        ),
    ]
